# Generated by Django 5.0.3 on 2026-03-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sessions/'),
        ),
    ]
